version: '3.8'
services:
  postgres:
    env_file:
      - .env
    image: postgres:${DATABASE_IMAGE_VERSION}
    container_name: ${DATABASE_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - ${DATABASE_EXTERNAL_PORT}:5432
    volumes:
      - ${PATH_TO_INIT_FILE}:/docker-entrypoint-initdb.d/init.sql
    networks:
      - database_net

  broker_messages:
    env_file:
      - .env
    image: rabbitmq:${BROKER_MESSAGES_IMAGE_VERSION}
    container_name: ${BROKER_MESSAGES_CONTAINER_NAME}
    ports:
      - ${BROKER_MESSAGES_PORT_1}:5672
      - ${BROKER_MESSAGES_PORT_2}:15672
    volumes:
      - ${BROKER_MESSAGES_DATA}:/var/lib/rabbitmq
      - ${BROKER_MESSAGES_LOG}:/var/log/rabbitmq
    networks:
      - broker_net

networks:
  database_net:
    driver: bridge
  broker_net:
    driver: bridge