spring:
  application:
    name: command-side-app
  datasource:
    driver-class-name: org.postgresql.Driver
    username: cqrs_user
    password: cqrs_pass
    url: jdbc:postgresql://localhost:5433/cqrs_db?currentSchema=command_schema
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10_000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost:5673,localhost15673

rabbit:
  exchanges:
    project:
      enable: true
      name: project
      queues:
        project:
          name: project
          route-keys: create, add-user, change-name, add-task
    task:
      enable: true
      name: task
      queues:
        task:
          name: task
          route-keys: create, change-name, change-task-status, assign-executor
    task-status:
      enable: true
      name: task-status
      queues:
        task-status:
          name: task-status
          route-keys: create, delete

server:
  port: 8081
springdoc:
  api-docs:
    path: /cqrs/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
