spring:
  application:
    name: command-side-app
  datasource:
    driver-class-name: org.postgresql.Driver
    username: cqrs_user
    password: cqrs_pass
    url: jdbc:postgresql://localhost:5433/cqrs_db?currentSchema=command_schema
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10_000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    username: guest
    password: guest
    addresses: localhost:5673,localhost15673
    queues:
      task-create:
        exchange: task
        routeKey: create
        name: task.create
      task-update:
        exchange: task
        routeKey: update
        name: task.update

server:
  port: 8081


